name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and fix the issue.
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: What went wrong?
    validations:
      required: true
  
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Run command '...'
        4. See error
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: What should have happened?
    validations:
      required: true
  
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: What actually happened? Include error messages if applicable.
    validations:
      required: true
  
  - type: input
    id: version
    attributes:
      label: Version
      description: What version/commit are you using?
      placeholder: e.g., main branch, commit abc123
    validations:
      required: true
  
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      value: |
        - OS: 
        - Node version: 
        - Neo4j version: 
        - Browser (if applicable): 
      render: markdown
    validations:
      required: true
  
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please paste any relevant log output
      render: shell
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, related issues, etc.)
