blank_issues_enabled: false
contact_links:
  - name: Question or Help
    url: https://github.com/localgod/polaris/issues/new?labels=question
    about: Ask a question or get help with using Polaris
  - name: Contributing Guide
    url: https://github.com/localgod/polaris/blob/main/CONTRIBUTING.md
    about: Learn how to contribute to the project
